### ISSUE TITLE
If resource does not exist, server sends fallback HTML instead of 404ing

### ISSUE THREAD

**Issue by ccnokes** [betsol/spa-server#1]
If you include a script that is not in root folder, the server will send the fallback HTML file instead of 404ing, which then causes some confusing errors because the browser attempts to parse HTML as JS. (It will say something like "unknown token '<'" because it tries to parse the opening doctype tag.) I wrote a middleware function to get around this, but it's breaking the livereload functionality. 

Here's the body of the function: 

``` javascript
//only send index.html for requests that don't include a file extension
//i.e. localhost/qc-coverage/123
//this way non-existent files will gracefully 404 and not be served as index.html
//this breaks livereload for some reason
if(path.extname(req.originalUrl) === '') {
    var readStream = fs.createReadStream('dist/index.html');
    readStream.pipe(res);
}
else {
    return next();
}
```

**Comment by slavafomin** [comment]
Thanks @ccnokes. I will try to implement it soon. Stay tuned.

**Comment by slavafomin** [comment]
Hey @ccnokes, could you please see this README file:
https://github.com/betsol/spa-server/blob/develop/README.md
(it's not yet implemented).

Will it suit your requirements? Do you have any suggestions/ideas?

Thanks!

**Comment by slavafomin** [comment]
@ccnokes, I've implemented the documented functionality in the `develop` branch. Feel free to test it yourself. I will merge it to master and make a backward incompatible release soon.

**Comment by ccnokes** [comment]
@slavafomin This looks awesome, exactly what I've been looking for in a plugin. I like the flexibility of your approach. Thanks!
