### ISSUE TITLE
Feature request: custom middleware support

### ISSUE THREAD

**Issue by ccnokes** [betsol/spa-server#2]
It'd be awesome if there was built-in support for livereload and optional middleware.

**Comment by slavafomin** [comment]
Good idea, I will look into it.

**Comment by slavafomin** [comment]
Hello @ccnokes!

Please review the custom middleware section of the new README:
https://github.com/betsol/spa-server/tree/develop#custom-middleware

If it's OK, I will release it.

I've also renamed this issue. Please create one issue per feature request.

**Comment by slavafomin** [comment]
I've released the `0.1.0` version that allows custom middleware (among other things). Feel free to test it. I will close this issue for now, but if you have any further requirements, please let me know.
