### ISSUE TITLE
Fallback not working

### ISSUE THREAD

**Issue by OmgImAlexis** [betsol/spa-server#9]
I've created a file to allow my current dir to used with spa-server. The problem I've got is that only `/` works. Everything else returns a 404 for example `/blog/x` returns `Cannot GET /blog/x`.

```
#!/usr/bin/env node

const path = require('path');
const mime = require('mime');
const serverFactory = require('spa-server');

const currentDir = process.cwd();
const fallback = path.join(currentDir, '/index.html');

const server = serverFactory.create({
    port: 3001,
    fallback
});

server.start();
```

**Comment by OmgImAlexis** [comment]
Docs may need a little works. This seems to have fixed the issue.

```
#!/usr/bin/env node

const path = require('path');
const mime = require('mime');
const serverFactory = require('spa-server');

const server = serverFactory.create({
    port: 3001,
    path: process.cwd(),
    fallback: 'index.html'
});

server.start();
```

**Comment by slavafomin** [comment]
Hello! Thank you for your interest in this module!

Every example in the documentation has explicit `path` property specified and the property itself is well documented.

**Comment by OmgImAlexis** [comment]
The example in the README has the exact issue I'm talking about. `fallbackConfig` isn't defined, I had assumed the fall back path was a server path not a URI. Maybe you could include a working fallbackConfig in the README?

```
var serverFactory = require('spa-server');

var server = serverFactory.create({
  path: './build',
  port: 80,
  fallback: fallbackConfig
});

server.start();
```

**Comment by slavafomin** [comment]
Actually, it is also documented and there is a chain of links leading to this section: https://github.com/betsol/spa-server#fallback-lookup
